"""Flatten main.tex into a single self-contained LaTeX file.

Recursively expands every ``\\input{...}`` (and ``\\include{...}``) command,
inlining the referenced file's contents. The resulting file contains the
preamble plus every section body in one raw ``.tex`` document.

Usage::

    python scripts/flatten.py                 # writes paper.tex next to main.tex
    python scripts/flatten.py --root main.tex --output paper.tex
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# Matches \input{...} or \include{...} that is not preceded by a %.
_INPUT_RE = re.compile(r"(?P<prefix>^|[^\\%])\\(?P<cmd>input|include)\{(?P<path>[^}]+)\}")


def _resolve(base_dir: Path, ref: str) -> Path:
    """Resolve a LaTeX input reference relative to ``base_dir``.

    LaTeX accepts references with or without the ``.tex`` extension.
    """
    candidate = (base_dir / ref).resolve()
    if candidate.suffix == "":
        with_ext = candidate.with_suffix(".tex")
        if with_ext.is_file():
            return with_ext
    if candidate.is_file():
        return candidate
    # Fall back to adding the extension unconditionally.
    with_ext = candidate.with_suffix(candidate.suffix + ".tex") if candidate.suffix else candidate.with_suffix(".tex")
    if with_ext.is_file():
        return with_ext
    raise FileNotFoundError(f"Cannot resolve LaTeX input: {ref!r} from {base_dir}")


def flatten(path: Path, project_root: Path, seen: set[Path] | None = None) -> str:
    """Return the fully expanded contents of ``path``."""
    if seen is None:
        seen = set()
    resolved = path.resolve()
    if resolved in seen:
        raise RuntimeError(f"Cycle detected while flattening: {resolved}")
    seen = seen | {resolved}

    text = resolved.read_text(encoding="utf-8")
    base_dir = resolved.parent

    def _replace(match: re.Match[str]) -> str:
        prefix = match.group("prefix")
        ref = match.group("path").strip()
        child = _resolve(base_dir, ref)
        expanded = flatten(child, project_root, seen)
        try:
            display = child.relative_to(project_root).as_posix()
        except ValueError:
            display = child.as_posix()
        header = f"% >>> begin {display}\n"
        footer = f"\n% <<< end {display}"
        return f"{prefix}{header}{expanded.rstrip()}{footer}\n"

    return _INPUT_RE.sub(_replace, text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default="main.tex", help="Top-level LaTeX file to flatten.")
    parser.add_argument("--output", default="paper.tex", help="Destination flattened file.")
    parser.add_argument(
        "--project-root",
        default=None,
        help="Project root used for relative paths in section markers (defaults to root file directory).",
    )
    args = parser.parse_args()

    root_path = Path(args.root).resolve()
    project_root = Path(args.project_root).resolve() if args.project_root else root_path.parent
    output_path = Path(args.output).resolve()

    banner = (
        "% !TEX root = paper.tex\n"
        f"% Auto-generated by scripts/flatten.py from {root_path.name}.\n"
        "% Do not edit by hand; edit the source .tex files and re-run the flattener.\n\n"
    )
    flattened = flatten(root_path, project_root)
    output_path.write_text(banner + flattened, encoding="utf-8")
    print(f"Wrote flattened LaTeX to {output_path}")


if __name__ == "__main__":
    main()
